baseURL = '/'
languageCode = 'en'
title = 'Pradeep Yendluri'
theme = 'hugo-cat'
PygmentsCodeFences = true
PygmentsStyle = "solarized-dark256"
pluralizelisttitles = "false"
paginate  = 15
disableHugoGeneratorInject = false
enableEmoji = true

[params]
ava = "/img/cat.png"
owner ="YNVP"
talk = "Hi..."
blogSection = ["blog"]
description = "Cat"
favicon = "/img/logo.svg"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[module]
  [module.hugoVersion]
    extended = true
    min = "0.111.3"
